[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:gunicorn]
command=/usr/local/bin/start_gunicorn.sh
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/gunicorn.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
priority=10

[program:n8n]
command=/usr/local/bin/start_n8n.sh
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/n8n_entrypoint.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
priority=20
